#
# Generated by erpcgen 1.14.0 on Thu Feb 26 08:29:50 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for ModemService
class ModemServiceClient(interface.IModemService):
    def __init__(self, manager):
        super(ModemServiceClient, self).__init__()
        self._clientManager = manager

    def is_modem_alive(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.IS_MODEM_ALIVE_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_bool()
        return _result

    def get_modem_info(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GET_MODEM_INFO_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = common.ModemInfo()._read(codec)
        return _result

    def get_sim_status(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GET_SIM_STATUS_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_string()
        return _result

    def get_signal_quality(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GET_SIGNAL_QUALITY_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = common.SignalQuality()._read(codec)
        return _result

    def is_registered(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.IS_REGISTERED_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_bool()
        return _result

    def list_esim_profiles(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.LIST_ESIM_PROFILES_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = common.ESimProfileList()._read(codec)
        return _result

    def switch_esim_profile(self, iccid):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.SWITCH_ESIM_PROFILE_ID,
                sequence=request.sequence))
        if iccid is None:
            raise ValueError("iccid is None")
        codec.write_string(iccid)

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_bool()
        return _result

    def get_active_iccid(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GET_ACTIVE_ICCID_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_string()
        return _result


# Client for TestService
class TestServiceClient(interface.ITestService):
    def __init__(self, manager):
        super(TestServiceClient, self).__init__()
        self._clientManager = manager

    def send_at_command(self, cmd, timeout_ms):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.SEND_AT_COMMAND_ID,
                sequence=request.sequence))
        if cmd is None:
            raise ValueError("cmd is None")
        codec.write_string(cmd)
        if timeout_ms is None:
            raise ValueError("timeout_ms is None")
        codec.write_uint32(timeout_ms)

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = common.AtResponse()._read(codec)
        return _result


