#
# Generated by erpcgen 1.14.0 on Thu Feb 26 08:29:50 2026.
#
# AUTOGENERATED - DO NOT EDIT
#


# Enumerators data types declarations
# eRPC service definitions for modem control via STM32H7.
#
# ModemService — structured methods used in production and testing.
# TestService  — raw AT passthrough for test-only operations.
#
# Service IDs are explicit to avoid collision with TextService (id=1).
# Signal quality fields use int16 with sentinel -128 for "not available"
# since eRPC has no nullable scalars.
class StatusCode:
    OK = 0
    Error = 1
    Timeout = 2
    NotConnected = 3


# Structures data types declarations
class ModemInfo(object):
    def __init__(self, manufacturer=None, model=None, firmware=None, imei=None):
        self.manufacturer = manufacturer # string
        self.model = model # string
        self.firmware = firmware # string
        self.imei = imei # string

    def _read(self, codec):
        self.manufacturer = codec.read_string()
        self.model = codec.read_string()
        self.firmware = codec.read_string()
        self.imei = codec.read_string()
        return self

    def _write(self, codec):
        if self.manufacturer is None:
            raise ValueError("manufacturer is None")
        codec.write_string(self.manufacturer)
        if self.model is None:
            raise ValueError("model is None")
        codec.write_string(self.model)
        if self.firmware is None:
            raise ValueError("firmware is None")
        codec.write_string(self.firmware)
        if self.imei is None:
            raise ValueError("imei is None")
        codec.write_string(self.imei)

    def __str__(self):
        return "<%s@%x manufacturer=%s model=%s firmware=%s imei=%s>" % (self.__class__.__name__, id(self), self.manufacturer, self.model, self.firmware, self.imei)

    def __repr__(self):
        return self.__str__()

class SignalQuality(object):
    def __init__(self, mode=None, rssi=None, rsrp=None, rsrq=None, sinr=None, rscp=None, ecio=None):
        self.mode = mode # string
        self.rssi = rssi # int16
        self.rsrp = rsrp # int16
        self.rsrq = rsrq # int16
        self.sinr = sinr # int16
        self.rscp = rscp # int16
        self.ecio = ecio # int16

    def _read(self, codec):
        self.mode = codec.read_string()
        self.rssi = codec.read_int16()
        self.rsrp = codec.read_int16()
        self.rsrq = codec.read_int16()
        self.sinr = codec.read_int16()
        self.rscp = codec.read_int16()
        self.ecio = codec.read_int16()
        return self

    def _write(self, codec):
        if self.mode is None:
            raise ValueError("mode is None")
        codec.write_string(self.mode)
        if self.rssi is None:
            raise ValueError("rssi is None")
        codec.write_int16(self.rssi)
        if self.rsrp is None:
            raise ValueError("rsrp is None")
        codec.write_int16(self.rsrp)
        if self.rsrq is None:
            raise ValueError("rsrq is None")
        codec.write_int16(self.rsrq)
        if self.sinr is None:
            raise ValueError("sinr is None")
        codec.write_int16(self.sinr)
        if self.rscp is None:
            raise ValueError("rscp is None")
        codec.write_int16(self.rscp)
        if self.ecio is None:
            raise ValueError("ecio is None")
        codec.write_int16(self.ecio)

    def __str__(self):
        return "<%s@%x mode=%s rssi=%s rsrp=%s rsrq=%s sinr=%s rscp=%s ecio=%s>" % (self.__class__.__name__, id(self), self.mode, self.rssi, self.rsrp, self.rsrq, self.sinr, self.rscp, self.ecio)

    def __repr__(self):
        return self.__str__()

class ESimProfile(object):
    def __init__(self, iccid=None, status=None, nickname=None, provider=None):
        self.iccid = iccid # string
        self.status = status # string
        self.nickname = nickname # string
        self.provider = provider # string

    def _read(self, codec):
        self.iccid = codec.read_string()
        self.status = codec.read_string()
        self.nickname = codec.read_string()
        self.provider = codec.read_string()
        return self

    def _write(self, codec):
        if self.iccid is None:
            raise ValueError("iccid is None")
        codec.write_string(self.iccid)
        if self.status is None:
            raise ValueError("status is None")
        codec.write_string(self.status)
        if self.nickname is None:
            raise ValueError("nickname is None")
        codec.write_string(self.nickname)
        if self.provider is None:
            raise ValueError("provider is None")
        codec.write_string(self.provider)

    def __str__(self):
        return "<%s@%x iccid=%s status=%s nickname=%s provider=%s>" % (self.__class__.__name__, id(self), self.iccid, self.status, self.nickname, self.provider)

    def __repr__(self):
        return self.__str__()

class ESimProfileList(object):
    def __init__(self, profiles=None):
        self.profiles = profiles # list<ESimProfile>

    def _read(self, codec):
        _n0 = codec.start_read_list()
        self.profiles = []
        for _i0 in range(_n0):
            _v0 = ESimProfile()._read(codec)
            self.profiles.append(_v0)

        return self

    def _write(self, codec):
        if self.profiles is None:
            raise ValueError("profiles is None")
        codec.start_write_list(len(self.profiles))
        for _i0 in self.profiles:
            _i0._write(codec)


    def __str__(self):
        return "<%s@%x profiles=%s>" % (self.__class__.__name__, id(self), self.profiles)

    def __repr__(self):
        return self.__str__()

class AtResponse(object):
    def __init__(self, status=None, response=None):
        self.status = status # StatusCode
        self.response = response # string

    def _read(self, codec):
        self.status = codec.read_int32()
        self.response = codec.read_string()
        return self

    def _write(self, codec):
        if self.status is None:
            raise ValueError("status is None")
        codec.write_int32(self.status)
        if self.response is None:
            raise ValueError("response is None")
        codec.write_string(self.response)

    def __str__(self):
        return "<%s@%x status=%s response=%s>" % (self.__class__.__name__, id(self), self.status, self.response)

    def __repr__(self):
        return self.__str__()

