#
# Generated by erpcgen 1.14.0 on Thu Feb 26 08:29:50 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for ModemService
class IModemService(object):
    SERVICE_ID = 2
    IS_MODEM_ALIVE_ID = 1
    GET_MODEM_INFO_ID = 2
    GET_SIM_STATUS_ID = 3
    GET_SIGNAL_QUALITY_ID = 4
    IS_REGISTERED_ID = 5
    LIST_ESIM_PROFILES_ID = 6
    SWITCH_ESIM_PROFILE_ID = 7
    GET_ACTIVE_ICCID_ID = 8

    def is_modem_alive(self):
        raise NotImplementedError()

    def get_modem_info(self):
        raise NotImplementedError()

    def get_sim_status(self):
        raise NotImplementedError()

    def get_signal_quality(self):
        raise NotImplementedError()

    def is_registered(self):
        raise NotImplementedError()

    def list_esim_profiles(self):
        raise NotImplementedError()

    def switch_esim_profile(self, iccid):
        raise NotImplementedError()

    def get_active_iccid(self):
        raise NotImplementedError()


# Abstract base class for TestService
class ITestService(object):
    SERVICE_ID = 3
    SEND_AT_COMMAND_ID = 1

    def send_at_command(self, cmd, timeout_ms):
        raise NotImplementedError()


