#
# Generated by erpcgen 1.14.0 on Thu Feb 26 08:29:50 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for ModemService
class ModemServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(ModemServiceService, self).__init__(interface.IModemService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IModemService.IS_MODEM_ALIVE_ID: self._handle_is_modem_alive,
                interface.IModemService.GET_MODEM_INFO_ID: self._handle_get_modem_info,
                interface.IModemService.GET_SIM_STATUS_ID: self._handle_get_sim_status,
                interface.IModemService.GET_SIGNAL_QUALITY_ID: self._handle_get_signal_quality,
                interface.IModemService.IS_REGISTERED_ID: self._handle_is_registered,
                interface.IModemService.LIST_ESIM_PROFILES_ID: self._handle_list_esim_profiles,
                interface.IModemService.SWITCH_ESIM_PROFILE_ID: self._handle_switch_esim_profile,
                interface.IModemService.GET_ACTIVE_ICCID_ID: self._handle_get_active_iccid,
            }

    def _handle_is_modem_alive(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.is_modem_alive()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.IS_MODEM_ALIVE_ID,
            sequence=sequence))
        codec.write_bool(_result)

    def _handle_get_modem_info(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.get_modem_info()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.GET_MODEM_INFO_ID,
            sequence=sequence))
        _result._write(codec)

    def _handle_get_sim_status(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.get_sim_status()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.GET_SIM_STATUS_ID,
            sequence=sequence))
        codec.write_string(_result)

    def _handle_get_signal_quality(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.get_signal_quality()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.GET_SIGNAL_QUALITY_ID,
            sequence=sequence))
        _result._write(codec)

    def _handle_is_registered(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.is_registered()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.IS_REGISTERED_ID,
            sequence=sequence))
        codec.write_bool(_result)

    def _handle_list_esim_profiles(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.list_esim_profiles()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.LIST_ESIM_PROFILES_ID,
            sequence=sequence))
        _result._write(codec)

    def _handle_switch_esim_profile(self, sequence, codec):
        # Read incoming parameters.
        iccid = codec.read_string()

        # Invoke user implementation of remote function.
        _result = self._handler.switch_esim_profile(iccid)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.SWITCH_ESIM_PROFILE_ID,
            sequence=sequence))
        codec.write_bool(_result)

    def _handle_get_active_iccid(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.get_active_iccid()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IModemService.SERVICE_ID,
            request=interface.IModemService.GET_ACTIVE_ICCID_ID,
            sequence=sequence))
        codec.write_string(_result)


# Client for TestService
class TestServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(TestServiceService, self).__init__(interface.ITestService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.ITestService.SEND_AT_COMMAND_ID: self._handle_send_at_command,
            }

    def _handle_send_at_command(self, sequence, codec):
        # Read incoming parameters.
        cmd = codec.read_string()
        timeout_ms = codec.read_uint32()

        # Invoke user implementation of remote function.
        _result = self._handler.send_at_command(cmd, timeout_ms)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.ITestService.SERVICE_ID,
            request=interface.ITestService.SEND_AT_COMMAND_ID,
            sequence=sequence))
        _result._write(codec)


